# Generated by Django 3.0.6 on 2020-06-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='DESCRIPTION'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='scope',
            field=models.CharField(blank=True, max_length=5, verbose_name='SCOPE'),
        ),
    ]
